name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: VTPortal
          package: .
env:
  AZURE_CLIENT_ID: ${{ secrets.AzureAppService_clientId }}
  AZURE_TENANT_ID: ${{ secrets.AzureAppService_tenantId }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AzureAppService_subscriptionId }}
  AZURE_CLIENT_SECRET: ${{ secrets.AzureAppService_clientSecret }}
